# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrATFO0YoL33mAn-LqGHoK5g32qs915u
"""

import pandas as pd
prices=[2999, 15999, 52999, 4999, 1999]
products=["Wireles Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"]
product_prices=pd.Series(prices,index=products)
print(product_prices)

print("Mean:", product_prices.mean())

print("Sum:",product_prices.sum())

print("Max:",product_prices.max())

print("Min:",product_prices.min())

print("Head (first 3 Elements):\n",product_prices.head(3))

print("Tail (first 3 Elemets):\n",product_prices.tail(2))

print("Apply (Adding 18% GST):\n", product_prices.apply(lambda x: f'₹{x+(x*0.18)}'))

print("Map (Formatting as Currency):\n", product_prices.map(lambda x:f"₹{x}.00"))

print("Sort by Index:\n", product_prices.sort_values())

print(product_prices.sort_values())

print(product_prices.sort_index())

print(product_prices.sort_index(ascending=False))

print("Value Counts:\n", product_prices.value_counts())

import pandas as pd
data={
"Product": ["Wireless Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"],
"Brand": ["SoundMax", "TechNova", "Bytecore", "TimeTrack", "EchoBoom"],
"Price": [2999, 15999, 52999, 4999,5678],
"Stock": [50, 30, 20, 40 ,60],
"BestSeller":[True,False,False,True,True]
}
df=pd.DataFrame(data)
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(3))
print(df.tail(2))

print(df)
print(df.loc[1, "Product"])
print(df.loc[2, "Product"])
print(df.loc[4, "Stock"])

print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,3])

print(df.iloc[3])
print(df.iloc[2])

print(df)
print("***********Using loc***************\n", df.loc[df['BestSeller']==True])
print("***********Using loc***************\n", df.loc[df['Stock']<40])
print("***********Using loc***************\n", df.loc[df['Price']<10000])

df_renamed = df.rename(columns={"Price": "Cost"})
print(df_renamed)
#df.rename(columns={"Product": "Product name"}, inplace=True)

df_grouped = df.groupby("Brand").agg({"Price": "sum", "Stock": "sum"})
print(df_grouped)

grouped=df.groupby("Brand").agg({"Price": ["mean", "max", "min"]})
print(grouped)

data2 ={
    "Brand": ["Soundmax", "TechNova", "Bytecore", "TimeTrack", "EchoBoom"],
    "Rating": [4.2, 4.5, 4.0, 4.1, 3.9],
    'discount':[28,40,16,10,5]
}
df_ratings = pd.DataFrame(data2)
print(df_ratings)

df_merged = df.merge(df_ratings, on="Brand")
print("Merged DataFrame (Adding Ratings):\n", df_merged)

new_data={
    "Product": ["Tablet"],
    "Brand": ["SmartWare"],
    "Price": [12999],
    "Stock": [25],
    "BestSeller":[True]
}
df_new = pd.DataFrame(new_data)
print(df_new)

df_concat = pd.concat([df, df_new], ignore_index=True)
print("Concatenated DataFrame:\n", df_concat)

print(df["Product"])

print(df[["Product", "Price","Stock"]])

df["Rank"] = df["Price"].rank(ascending=False)
print(df)

df["Price"] = df["Price"].astype(float)
print(df)

df["Rank"] = df["Price"].rank(ascending=False)
print(df)
print(df.sort_values(by="Rank", ascending=True))
print(df.sort_values(by="Rank", ascending=False))

df1=pd.DataFrame({
    'ID':[1,2],
    'Name':['Alice','Bob'],
    'Age':[25,30]
})
df2=pd.DataFrame({
    'ID':[3,4],
    'Name':['Charlie','david'],
    'Age':[28,35]
})
df_combined=pd.concat([df1,df2],axis=0)
print(df_combined)

print(df)
df.pivot_table(values="Price",index="Brand",columns="Stock",aggfunc="max")

import pandas as pd
import numpy as np
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,np.nan,5],
    'C':[10,np.nan,np.nan,40,50]
}
df=pd.DataFrame(data)
print("Original Dataframe With Missing Value:")
print(df)

df_dropna=df.dropna()
print('\nDataFrame after droping rows with NaN values:')
print(df_dropna)

df_fillna=df.fillna(0)
print(df_fillna)

df_interpolate=df.interpolate()
print("\nDataFrame after filling NaN values using interpolatin")
print(df_interpolate)

from google.colab import files
uploaded=files.upload()

import pandas as pd
df=pd.read_csv("emails.csv")
print(df)

import pandas as pd
import requests
from bs4 import BeautifulSoup

URL='https://timely-sunshine-e821b3.netlify.app/'
#URL='https://codegnan.com/'

page=requests.get(URL)

page.status_code

htmlCode= page.text
print(htmlCode)

soup=BeautifulSoup(htmlCode,'html.parser')
print(soup)

content = soup.find_all('div', attrs={'class' : 'a'})
for i in content:
  print("Div:",i,end='\n\n\n\n\n')

content = soup.find('div', attrs={'class' : 'name'})
text=content.text
print(text)

content=soup.find('div', attrs={'class' : 'price'})
text= content.text.strip()
print(text)

content=soup.find('div', attrs={'class' : 'image'})
print(content)

img_tag = content.find('img')
print(img_tag)

img_src = img_tag['src']
print(img_src)

items = soup.find_all('div', class_='a')
names=[]
prices=[]
images=[]
for item in items:
    name=item.find('div', class_='name').text.strip()
    price=item.find('div', class_='price').text.strip()
    image_tag=item.find('div', class_='image').find('img')
    image_src=image_tag['src'] if image_tag else None
    names.append(name)
    prices.append(price)
    images.append(image_src)
print("Names:", names)
print("Prices:", prices)
print("Images:",images)

df = pd.DataFrame({'Product_Name' : names,'MRP' : prices, 'Image_SRC': images})

df

df.to_csv('productdetails.csv', header=True, index=False)

from google.colab import files
files.download('productdetails.csv')