# -*- coding: utf-8 -*-
"""numpy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMBjT1mDN34kr4jnrtO4otlMXy0eWYmK
"""

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

print(np.linalg.inv(A))

print(np.linalg.det(A))

A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

import numpy as np
arr=np.array([10,20,30])
view_arr=arr.view()
view_arr[0]=100
print(arr,view_arr)

copy_arr=arr.copy()
copy_arr[0]=200
print(arr,copy_arr)

unique_vals=np.unique(arr)
print(unique_vals)

arr=np.array([3,1,4,1,5,9,2,6])
sorted_arr=np.sort(arr)
print(sorted_arr)

arr=np.array([10,20,30,40,50])
print(arr%20==0)
print(arr[arr%20==0])

arr=np.array([1,2,3,4,5])
print(np.cumsum(arr)) #[1,3,6,10,15]
print(np.cumprod(arr)) #[1,2,6,24,120]

print(np.min(arr))
print(np.max(arr))

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

arr=np.array([4,9,16,25,36])

print(arr + 1)
print(arr * 2)
print(arr ** 2)
print(np.sqrt(arr))

matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1,1])
print(matrix[2,1])
print(matrix[0,2])
print(matrix[0:3,0])
print(matrix[0:3,1])
print(matrix[0:2,1:3])

arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

transposed= arr.T
print(transposed)

a=np.array([[1,2,3,4],[1,2,3,4]])
flattened= a.flatten()
print(flattened)

reshaped=arr.reshape(4,3)
print(reshaped)

arr=np.array([[1,2],[4,5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)

l=['html','css','javascript','python','mysql']
rand_choice=np.random.choice(1,4)
print(rand_choice)

rand_int=np.random.randint(1,6,(5,5))
print(rand_int)

rand_float=np.random.rand(3,2)
print(rand_float)

rand_int=np.random.randint(30,60)
print(rand_int)

np.random.seed(10)
rand_int=np.random.randint(6)
print(rand_int)

lin_space=np.linspace(50, 100, 6)
print(lin_space)

range_arr=np.arange(1,30,2)
print(range_arr)

full_array=np.full((2,3),100)
print(full_array)

identity=np.eye(7)
print(identity)

ones=np.ones((3,4))
print(ones)

zeros=np.zeros((3,4))
print(zeros)

import numpy as np
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')
arr2=np.array([1,2,3,4,5,6])
print("2-dim",arr2,sep='\n',end='\n\n')
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("multi-dim",arr3,sep='\n')