# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JisavK1oFW8TvX4lkrvgzrv2onWEUISe
"""

import matplotlib.pyplot as plt
hours=[1,2,3,4,5,6,7,8]
visitors=[50,60,65,70,90,120,110,130]
plt.plot(hours, visitors,
         color="red",
         marker="o",
         linestyle="-",
         linewidth=1,
         alpha=1,
         label="Visitors")
plt.title("Website Visitors Per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Visitors")
plt.legend()

plt.grid(True,linestyle="-", alpha=0.3)
plt.show()

import matplotlib.pyplot as plt
products=["Laptop", "Mobile","Tablet", "Headphones", "Smartwatch"]
sales= [250, 400, 150, 300, 180]
plt.bar(products, sales, color="green",edgecolor='red',alpha=0.5,width=0.5)
plt.title("Product Sales Comparison")
plt.xlabel("Products")
plt.ylabel("Units Sold")
plt.show()

marks=[45,55,60,72,68,80,90,55,67,70,
       85,40,60,75,78,82,95,50,62,65,
       58,73,77,69,71,88,92,55,63,59]
plt.hist(marks, bins=10, histtype='bar',edgecolor="black")
plt.title("Distribution of Student Marks")
plt.xlabel("Marks Range")
plt.ylabel("Number of Students")
plt.show()

import matplotlib.pyplot as plt
brands=["Apple", "Samsung", "Xiaomi", "oppo", "Others"]
market_share=[30,25,20,10,15]
plt.pie(market_share,
        labels=brands,
        autopct="%.2f%%",
        startangle=0,
        colors=["gold", "skyblue", "lightcoral", "lightgreen", "violet"],
        explode=[0.1, 0 , 0 ,0 , 0],
        shadow=True)
plt.title("Mobile Market Share 2025")
plt.show()

import matplotlib.pyplot as plt
scores=[
[70, 85, 59, 92, 91, 100, 89],
[70, 85, 90, 92, 88, 76, 95],
[65, 70 ,68 ,72 ,75 ,80 , 85],
[62, 60, 61, 90, 65, 63, 67],
[70, 85, 8, 50, 92, 91, 100],
]
plt.boxplot(scores,
           patch_artist=True,
           boxprops=dict(facecolor="lightblue"),
           medianprops=dict(color='red',linewidth=2),
           whiskerprops=dict(color='green'),
           capprops=dict(color='black'),
           notch=False,
           vert=True,
           labels=["A", "B", "C", "D", "E"])
plt.title("Exam Scores Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True,linestyle='--',alpha=0.7)
plt.show()